apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/igalane/argocd-test.git
      revision: HEAD
      directories:
      - path: 'multiappmultienv/base/*'
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: 'qa-apps'
      source:
        repoURL: https://github.com/igalane/argocd-test.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'qa'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true