apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: firstapp
  template:
    metadata:
      labels:
        deployment: firstapp
    spec:
      containers:
      - name: firstapp-container
        image: ishwargalane/sysinfo-app:app1-v1.0
        env:
        - name: BG_COLOR
          valueFrom:
            configMapKeyRef:
              name: firstapp-cm
              key: BG_COLOR
        - name: DEPLOY_ENV
          valueFrom:
            configMapKeyRef:
              name: firstapp-cm
              key: DEPLOY_ENV