apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: firstappcommonlabel
  deployment: firstapp

resources:
- deployment.yaml
- service.yaml
- configMap.yaml

images:
- name: ishwargalane/sysinfo-app
  newName: ishwargalane/sysinfo-app
  newTag: app1-v1.0