apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-base-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/igalane/argocd-test.git
    targetRevision: HEAD
    path: multiappmultienv/base
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
