apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    variant: qa

namePrefix: qa-
commonAnnotations:
  note: Hello, This is QA Environment!
resources:
- ../../base

patches:
- path: configMap.yaml

images:
- name: ishwargalane/sysinfo-app
  newName: ishwargalane/sysinfo-app
  newTag: app1-v1.0