apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    variant: prod

namePrefix: prod-
commonAnnotations:
  note: Hello, This is production!
resources:
- ../../base

patches:
- path: deployment.yaml
- path: configMap.yaml
