apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  note: Hello, This is QA Environment!
configMapGenerator:
- behavior: merge
  envs:
  - config.properties
  name: firstapp-cm
images:
- name: ishwargalane/sysinfo-app
  newName: ishwargalane/sysinfo-app
  newTag: app1-v0.1
kind: Kustomization
namePrefix: qa-
namespace: qa
resources:
- ../../../base/firstapp
