apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: qa-
commonAnnotations:
  note: Hello, This is QA Environment!
resources:
- ../../../firstapp

images:
- name: ishwargalane/sysinfo-app
  newName: ishwargalane/sysinfo-app
  newTag: app1-v1.0

configMapGenerator:
- name: firstapp-cm
  behavior: merge
  envs: 
  - config.properties