apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-base-app
  namespace: argocd
spec:
  project: qa-apps
  source:
    repoURL: https://github.com/igalane/argocd-test.git
    targetRevision: HEAD
    path: multiappmultienv/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
