apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: firstapp
    spec:
      containers:
      - name: firstapp-container
        image: ishwargalane/sysinfo-app:app1-v0.1 #This can be latest on DEV env 
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: firstapp-cm
