apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: firstappcommonlabel
  deployment: firstapp

resources:
- deployment.yaml
- service.yaml

images:
- name: ishwargalane/sysinfo-app
  newName: ishwargalane/sysinfo-app
  newTag: app1-v1.0

configMapGenerator:
- name: firstapp-cm  
  envs: 
  - config.properties