apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: firstappcommonlabel
  deployment: firstapp
configMapGenerator:
- envs:
  - config.properties
  name: firstapp-cm
images:
- name: ishwargalane/sysinfo-app
  newName: ishwargalane/sysinfo-app
  newTag: app1-v0.1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
