apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

namePrefix: qa-
commonAnnotations:
  note: Hello, This is QA Environment!
resources:
- ../../../base/secondapp

images:
- name: ishwargalane/sysinfo-app
  newName: ishwargalane/sysinfo-app
  newTag: app2-v1.0

configMapGenerator:
- name: secondapp-cm
  behavior: merge
  envs: 
  - config.properties