apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondapp-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        deployment: secondapp
    spec:
      containers:
      - name: secondapp-container
        image: ishwargalane/sysinfo-app:app2-v1.0 #This can be latest on DEV env 
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: secondapp-cm
