apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: secondappcommonlabel
  deployment: secondapp
configMapGenerator:
- envs:
  - config.properties
  name: secondapp-cm
images:
- name: ishwargalane/sysinfo-app
  newName: ishwargalane/sysinfo-app
  newTag: app2-v0.1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
